```{r}
install.packages("MPsychoR")
install.packages("psych")
```

```{r}
library(MPsychoR)
library(psych)
data("Rmotivation")
```

```{r}
ind<-grep("hyb",colnames(Rmotivation))
HybMotivation<-na.omit(Rmotivation[,ind])
k<-ncol(HybMotivation)
```

```{r}
vcmat<-cov(HybMotivation)
```

```{r}
sigma2_Xi<-tr(vcmat)
```

```{r}
sigma2_X<-sum(vcmat)
```

```{r}
cronalpha<-k/(k-1)*(1-sigma2_Xi/sigma2_X)
round(cronalpha,2)
```

```{r}
sqrt(sigma2_X)*sqrt(1-cronalpha)
```

```{r}
alpha.hyb<-psych::alpha(HybMotivation)
```

```{r}
round(alpha.hyb$total[1],2)
```

```{r}
glb(HybMotivation)
```

```{r}
omega(HybMotivation)
```

```{r}
library(reshape2)
Hyb1<-data.frame(HybMotivation,person=1:nrow(HybMotivation))
Hyblong<-melt(Hyb1,id.vars = c("person"),variable.name = "item")
Hyblong$person<-as.factor(Hyblong$person)
```

```{r}
summary(aov(value~person+item,data=Hyblong))
```

```{r}
round((0.85-0.15)/0.85,2)
```

```{r}
library(lme4)
icchyb<-ICC(HybMotivation)
```

```{r}
icchyb
```

```{r}
sqrt((0.85-0.15)/19)
sqrt((31.88-0.15)/777)
```

```{r}
library(lme4)
```

```{r}
VarCorr(lmer(value~(1|person)+(1|item),data=Hyblong))
```

```{r}
#install.packages("gtheory")
install.packages("./gtheory_0.1.2.tar.gz", repos = NULL, type="source")
```

```{r}
library(gtheory)
```

```{r}
gfit<-gstudy(data=Hyblong,formula = value~(1|person)+(1|item))
```

```{r}
gfit
```

```{r}
dfit<-dstudy(gfit,colname.objects = "person",colname.scores = "value",data=Hyblong)
```

```{r}
dfit
```

```{r}
round(dfit$generalizability,3)
```

```{r}
data("Lakes")
phydat<-subset(Lakes,subtest=="physical")
phydat$item<-droplevels(phydat$item)
head(phydat)
```

```{r}
formula<-score~(1|personID)+(1|raterID)+(1|item)+(1|personID:raterID)+(1|personID:item)+(1|raterID:item)
```

```{r}
gfit<-gstudy(formula=formula,data=phydat)
```

```{r}
gfit
```

```{r}
dfit<-dstudy(gfit,colname.objects = "personID",colname.scores = "score",data=phydat)
```

```{r}
dfit
```
