```{r}
library(MPsychoR)
data("YouthDep")
item1<-YouthDep[,1]
levels(item1)<-c("0","1","1")
item2<-YouthDep[,14]
levels(item2)<-c("0","1","1")
```

```{r}
table(item1,item2)
```

```{r}
library(psych)
tetcor<-tetrachoric(cbind(item1,item2))
tetcor
```

```{r}
draw.tetra(0.35,1.16,0.36)
```

```{r}
item1<-YouthDep[,1]
item2<-YouthDep[,14]
polcor<-polychoric(cbind(item1,item2))
polcor
```

```{r}
?draw.tetra
```

```{r}
DepItems<-YouthDep[,1:26]
Depnum<-data.matrix(DepItems)-1
```

```{r}
Rdep<-polychoric(Depnum)
Rdep
```

```{r}
data("Rmotivation")
vind<-grep("ext|int",colnames(Rmotivation))
Rmotivation1<-Rmotivation[,vind]
Rmot1<-tetrachoric(Rmotivation1,smooth=FALSE)
```
```{r}
Rmot1
```
```{r}
tail(round(eigen(Rmot1$rho)$values,3))
```

```{r}
Rmot<-tetrachoric(Rmotivation1)
tail(round(eigen(Rmot$rho)$values,3))
```
```{r}
Rmot$rho
```
```{r}
motFA<-fa(Rmot$rho,nfactors = 2,rotate = "none",fm="ml")
```
```{r}
print(motFA$loadings,cutoff = 0.2)
```

```{r}
motFA$loadings
```
 
```{r}
motFA$loadings[,c(1,2)]
```
 
```{r}
round(motFA$communality,2)
```
```{r}
motFA2<-fa(Rmot$rho,nfactors = 2,rotate = "varimax",fm="ml")
```
 
```{r}
motFA2$loadings
```
 
 
```{r}
factor.plot(motFA2)
```

```{r}
Rmot2<-tetrachoric(Rmotivation[,1:36])
motFA3<-fa(Rmot2$rho,nfactors = 3,rotate = "oblimin",fm="ml")
motFA3$loadings
```
```{r}
round(motFA3$Phi,3)
```

```{r}
motFA2<-fa(Rmotivation1,nfactors = 2,rotate = "varimax",cor="tet",fm="ml",scores = "regression",missing = TRUE,impute = "median")
```

```{r}
motFA2$loadings
```

```{r}
dim(motFA2$scores)
```

```{r}
head(motFA2$scores)
```
```{r}
motFA2$score.cor
```

